# Generated by Django 2.0.1 on 2018-01-31 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FollowMeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='id_user',
            new_name='user',
        ),
    ]
