# Generated by Django 2.0.1 on 2018-02-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoApp', '0002_waypoint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='date',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waypoint',
            name='hour',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
